name: Convert jupyter notebook readme into markdown 

on: push

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: install jupyter
      run: >-
        python -m
        pip install
        jupyter
        --user

    - name: convert to markdown
      run: jupyter nbconvert README.ipynb --to markdown

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate README.md from README.ipynb